config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "/painel", to: 'home#index'
  resources :home, only: :index
  resources :collections, only: [:show, :index]

  resources :user_instagram, only: [:new, :create]

  resources :oauth do
    collection do
      get :connect
      get :callback
    end
  end

  resources :media, only: [:create, :destroy] do
    member do
      get :download
      post :black_list
    end
  end

  get "/landscape", to: 'home#landscape'

  root to: 'user_instagram#new'
end

app/models/media.rb
class Media < ActiveRecord::Base
  validates :media_ig_id, presence: true
  validates :user_name, presence: true
  validates :post_url, presence: true
  validates :user_avatar_url, presence: true
  validates :url_thumb, presence: true
  validates :url_standard, presence: true
  
  validates :longitute, presence: true
  validates :latitude, presence: true
  validates :city, presence: true

  validates :created_at_ig, presence: true
end   

app/models/media_black_list.rb
class MediaBlackList < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :instagram_username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def client
    @instagram_client ||= InstagramClientFactory.get_instance
  end

end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  def show
    @items = SplitByDate.perform(Media.where(city_slug: params[:id]))
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recent_huhackday = FilterValidMedia.from(client.tag_recent_media('fotografohu'))
  end

  def landscape
  end
end

app/controllers/media_controller.rb
class MediaController < ApplicationController
  respond_to :js

  def create
    @media = Media.new

    @media.media_ig_id = media_params[:id]
    @media.user_name = media_params[:caption][:from][:username]
    @media.post_url = media_params[:link]
    @media.user_avatar_url = media_params[:caption][:from][:profile_picture]
    @media.url_thumb = media_params[:images][:thumbnail][:url]
    @media.url_standard = media_params[:images][:standard_resolution][:url]
    @media.longitute = media_params[:location][:longitude]
    @media.latitude = media_params[:location][:latitude]
    @media.city = GeoLocation.get_city_name(media_params[:location][:latitude], media_params[:location][:longitude])
    @media.city_slug = @media.city.parameterize
    @media.created_at_ig = DateTime.strptime(media_params[:created_time],'%s')

    @user = User.where(instagram_username: @media.user_name).first

    if @user && @media.save!
      MainMailer.invite_user(@user.email, @media.url_standard).deliver_later
      @success = true
    else
      # client.create_media_comment(@media.media_ig_id, "Uhuu! Sua imagem foi selecionada por nós.\nCopie o link abaixo e cole no seu navegador para concorrer!\n\n#{new_user_registration_path}")
      @success = false
    end
    render :create
  end

  def download
    @media = Media.find(params[:id])
    require 'open-uri'

    url = @media.url_standard
    data = open(url).read
    send_data data, :filename=>"photo.jpg"
  end

  def black_list
    @media_blacklist = MediaBlackList.new(media_ig_id: params[:id])
    if @media_blacklist.save!
      @success = true
    else
      # client.create_media_comment(@media.media_ig_id, "Uhuu! Sua imagem foi selecionada por nós.\nCopie o link abaixo e cole no seu navegador para concorrer!\n\n#{new_user_registration_path}")
      @success = false
    end
    render :black_list
  end

  def destroy
    Media.destroy(params[:id])

    redirect_to :back
  end

  private

  def media_params
    params.require(:media).permit(:created_time, :link, :location, :id,  :caption => [:from => [:username, :profile_picture] ], :images => [:standard_resolution => [:url], :thumbnail => [:url]], :location => [:latitude, :longitude])
  end
end

app/controllers/oauth_controller.rb
class OauthController < ApplicationController
  def connect
    redirect_to Instagram.authorize_url(:redirect_uri => callback_oauth_index_url)
  end

  def callback
    response = Instagram.get_access_token(params[:code], :redirect_uri => callback_oauth_index_url)
    session[:access_token] = response.access_token
    redirect_to root_path
  end
end

app/controllers/user_instagram_controller.rb
class UserInstagramController < ApplicationController
  before_filter :configure_devise_params, if: :devise_controller?
  def configure_devise_params
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:email, :instagram_username, :password, :password_confirmation)
    end
  end

  def new
    @user = User.new
  end

  def create
    generated_password = Devise.friendly_token.first(8)
    @user = User.new(user_params)
    @user.password = generated_password
    if @user.save && params[:sign_up]
      flash[:notice] = "Cadastro efetuado com sucesso!"
      redirect_to root_path
    else
      flash[:alert] = "Dados inválidos!"
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :instagram_username)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def collections
    @collections = Media.select(:city_slug).uniq
  end

end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def city_by_lat_long(lat, lon)
    city_name = GeoLocation.get_city_name(lat, lon)
    if city_name
      "#" + city_name.downcase.gsub(/\s+/, "")
    else
      ""
    end
  end
end

app/helpers/oauth_helper.rb
module OauthHelper
end

app/views/collections/_gallery.html.erb
<div class="gallery">
  <% @items.each do |year, months| %>
    <% months.each do |month, items| %>
      <h2> <%= "#{month.upcase} #{year}" %> </h2>
      <hr class="month-separator">
      <div class="month row">
        <% items.each do |item| %>
          <div class="col-sm-3">
            <div class="media darken">
              <div class="image">
                <div class="image-background">
                  <%= image_tag(item.url_thumb, class: 'img-thumbnail',
                  :'data-image-standard'=> item.url_standard) %>
                </div>
                <div class="actions row">
                  <div class="col-sm-6 text-left">
                      <%= link_to "", download_medium_path(id: item.id), method: :get, class: 'download' %>
                  </div>
                  <div class="col-sm-6 text-right">
                    <%= link_to "", medium_path(id: item.id), class: 'trash', method: :delete, data: { confirm: 'Tem certeza, seu bizonho?' } %>
                  </div>
                </div>
              </div>
              <div class="user">
                <%= image_tag(item.user_avatar_url, class: 'img-profile') %>
                <span class="username"><%= item.user_name %></span>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

<%= render 'shared/modal', actions: 'shared/modal_collection_actions' %>

app/views/collections/show.html.erb
<h1 class="title">#<%= params[:id] %></h1>

<div class="gallery">
  <% @items.each do |year, months| %>
    <% months.each do |month, items| %>
      <h2> <%= "#{month.upcase} #{year}" %> </h2>
      <hr class="month-separator">
      <div class="month row">
        <% items.each do |item| %>
          <div class="col-sm-3">
            <div class="media darken">
              <div class="image">
                <div class="image-background">
                  <%= image_tag(item.url_thumb, class: 'img-thumbnail',
                  :'data-image-standard'=> item.url_standard) %>
                </div>
                <div class="actions row">
                  <div class="col-sm-6 text-left">
                      <%= link_to "", download_medium_path(id: item.id), method: :get, class: 'download' %>
                  </div>
                  <div class="col-sm-6 text-right">
                    <%= link_to "", medium_path(id: item.id), class: 'trash', method: :delete, data: { confirm: 'Tem certeza, seu bizonho?' } %>
                  </div>
                </div>
              </div>
              <div class="user">
                <%= image_tag(item.user_avatar_url, class: 'img-profile') %>
                <span class="username"><%= item.user_name %></span>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

<%= render 'shared/modal', actions: 'shared/modal_collection_actions' %>

app/views/home/index.html.erb
<div class="gallery row">
  <% @recent_huhackday.each do |item| %>
    <div class="col-sm-3" id="<%= item['id'] %>">
      <div class="media">
        <div class="city">
          <%= city_by_lat_long(item['location']['latitude'], item['location']['longitude']) %>
        </div>
        <div class="image">
          <%= image_tag(item['images']['thumbnail']['url'], class: 'img-thumbnail',
          :'data-image-standard'=> item['images']['standard_resolution']['url']) %>
          <div class="actions row">
            <div class="col-sm-6 text-left">
              <%= link_to "", media_path(media: item), method: :post, remote: true, class: 'heart' %>
            </div>
            <div class="col-sm-6 text-right">
              <%= link_to "", black_list_medium_path(id: item['id']), method: :post, remote: true, class: 'trash' %>
            </div>
          </div>
        </div>
        <div class="user">
          <%= image_tag(item['user']['profile_picture'], class: 'img-profile') %>
          <span class="username"><%= item['user']['username'] %></span>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= render 'shared/modal', actions: 'shared/modal_dashboard_actions' %>

app/views/home/landscape.html.erb
<div class="landscape">
  <div class="row">
    <div class="col-sm-12">
      <h1>No HU Rewards suas fotos valem muito</h1>
      <%= image_tag 'iphone.jpg', class: "iphone" %>
      <div class="signup">
        <h2>Passo 1 - Cadastre-se</h2>
        <p>É necessário que você faça um pequeno cadastro para que possamos <em>entrar em contato com você</em> caso sua foto seja selecionada. Informe um <em>email para contato</em> e seu <em>username no instagram</em>.</p>
        <%= render 'devise/registrations/new' %>

      </div>
     </div>
  </div>
  <div class="row">

  </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<div id='flash-messages'>
  <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to '', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse nav-cities">
      <% if collections.size %>
        <ul class="nav navbar-nav pull-right">
          <div class="dropdown">
            <a href="#" class="dropdown-toggle collections-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Filtrar Cidades <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% collections.each do |collection| %>
                <li><%= link_to("##{collection.city_slug}", collection_path(id: collection.city_slug)) %></li>
              <% end %>
            </ul>
          </div>
        </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Hackday" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Hackday" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <div class='container'>
        <%= yield %>
       </div>
    </main>
  </body>
</html>

app/views/media/black_list.js.erb
<% if @success %>
  HuReward.FlashMessage.success('Uhuu! Foto excluída!');
<% else %>
  HuReward.FlashMessage.error('Vesh! Deu ruim...');
<% end %>

app/views/media/create.js.erb
<% if @success %>
  HuReward.FlashMessage.success('Uhuu! Foto favoritada!');
<% else %>
  HuReward.FlashMessage.error('Vesh! Deu ruim...');
<% end %>

app/views/shared/_modal.html.erb
<div class="modal fade modal-gallery" id="media-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="modal-city"></h4>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-sm-6">
            <div class="user">
              <img src="" alt="" class="img-profile">
              <span class="username"></span>
            </div>
          </div>
          <div class="col-sm-6">
            <!-- <%= render actions %> -->
          </div>
        </div>
        <img src="" alt="" class="image">
      </div>
    </div>
  </div>
</div>

app/views/shared/_modal_collection_actions.html.erb
<div class="actions text-right">
  <%= link_to "", media_path, method: :post, remote: true, class: 'download' %>
  <%= link_to "", "#", class: 'trash' %>
</div>

app/views/shared/_modal_dashboard_actions.html.erb
<div class="actions text-right">
  <%= link_to "", media_path, method: :post, remote: true, class: 'heart' %>
  <%= link_to "", "#", class: 'trash' %>
</div>

app/views/user_instagram/new.html.erb
<div class="landscape">
  <div class="row">
    <div class="col-sm-12">
      <h1>No HU Rewards suas fotos valem muito</h1>

      <div class='col-sm-3'>
        <%= image_tag 'iphone.jpg', class: "iphone" %>
      </div>
      <div class='col-sm-9'>
        <div class="signup">
          <h2>Passo 1 - Cadastre-se</h2>
          <p>É necessário que você faça um pequeno cadastro para que possamos <strong>entrar em contato com você</strong> caso sua foto seja selecionada. Informe um <strong>email para contato</strong> e seu <strong>username no instagram</strong>.</p>
            <%= form_for @user, url: user_instagram_index_path do |f| %>
            <div class="row">
            <div class='col-sm-3'>
              <div class="form-group">
                <%= f.label :email, "Email para contato" %>
                <%= f.email_field :email, autofocus: true, placeholder: "Digite seu email", class: "form-control" %>
              </div>
            </div>
            <div class='col-sm-3'>
              <div class="form-group">
                <%= f.label :instagram_username, "Usuário no Instagram" %>
                <%= f.text_field :instagram_username, placeholder: "Digite seu usuário",class: "form-control" %>
              </div>
            </div>
            <div class='col-sm-3'>
              <div class="form-group">
                <%= f.submit t('.sign_up', :default => "Vou Participar"), class: "btn btn-primary button-signup" %>
              </div>
            </div>
            <div class='col-sm-9'>
              <div class="form-group">
                <%= check_box_tag :sign_up, value: true, class: "inputAccept" %> <span class="inputAccept">Li e aceito os <%= link_to 'termos de uso de imagem', '#', data: { toggle: 'modal', target: '#terms-modal' } %>.</span>
              </div>
           </div>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-12">
    <div class='col-sm-3'>
    </div>
    <div class='col-sm-9'>
      <h2>Passo 2 - Hashtag</h2>
    </div>
  </div>
  <div class="col-sm-12">
    <div class="digauhu">
      <span class="title-hashtag">
        #DIGAUHUU <br>
      </span>
      <span>
        Para enviar sua imagem é simples, basta seguir os passos abaixo: <br>
        - Postar sua foto no Instagram com a <strong>hashtag #digauhuu na legenda</strong>.<br>
        - No momento da postagem<strong> ativar a geolocalização</strong>.<br>
        - Seu perfil do Instagram precisa ser <strong>público</strong>.<br>
      </span>
    </div>
  </div>
</div>

<div class="row credits">
  <div class="col-sm-12">
    <div class='col-sm-3'>
    </div>
    <div class='col-sm-9'>
      <h2>Passo 3 - Receba créditos</h2>
    </div>
    <div class='col-sm-3'><%= image_tag 'creditos1.jpg' %></div>
    <div class='col-sm-4'><%= image_tag 'creditos2.jpg' %></div>
    <div class='col-sm-5'>
      <span>Se sua foto for aprovada você <strong>receberá R$ 10,00 em créditos</strong> diretamente na sua conta do HU. <br><br>
      Além disso, suas fotos serão <strong>utilizadas em nossas campanhas e site</strong> com uma marca d`água com seu usuário do Instagram nela. <br><br>
      É o seu <strong>trabalho sendo divulgado no maior site de viagem da América Latina!</strong></span>
    </div>
    <div class="col-sm-12"><%= image_tag 'creditos3.jpg' %></div>
  </div>
</div>

<div class="row credits">
  <div class="col-sm-12">
      <h2 class="text-center">_______ Créditos _______</h2>
      <div class="social">
        <%= link_to "", "https://pt-br.facebook.com/hotelurbanobr", class: 'facebook' %>
        <%= link_to "", "https://twitter.com/hotel_urbano", class: 'twitter' %>
        <%= link_to "", "https://plus.google.com/+HotelUrbano", class: 'googleplus' %>
      </div>
  </div>
</div>

<footer class="footer-landscape">
  <p class="text-center">
    <strong>Alguma dúvida?</strong><br>
    (21) 2108-8845
  </p>
</footer>

<div class="modal fade modal-terms" id="terms-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="modal-city">Regulamento - #huhackday Instagram</h4>
      </div>
      <div class="modal-body row">
        <p>
          O concurso “#huhackday” é realizado pelo Hotel Urbano Viagens e Turismo S.A., sediado na Avenida Ayrton Senna nº 2150, bl. I, sala 204, Barra da Tijuca, CEP 22775-900, inscrito no CNPJ/MF sob o nº 12.954.744/0001-24 (doravante denominado simplesmente "Hotel Urbano”), e é aberta a todas as pessoas físicas capazes, maiores de 18 anos, residentes no Brasil, que desejarem participar.
        </p>
        <p>
          1. SOBRE O CONCURSO
          O concurso intitulado “#huhackday” será realizado através da participação voluntária e gratuita dos interessados, sem quaisquer modalidades de sorteio ou pagamento pelos participantes, nem vinculação à aquisição ou ao uso de qualquer produto, bem, direito ou serviço do Hotel Urbano. 
          O intuito do concurso é premiar os viajantes que enviarem fotos e vídeos que forem selecionados pelo HU para uso de conteúdo institucional e de anúncios de venda da empresa.
        </p>
        <p>
          2. PARTICIPANTES
          O presente concurso é aberto a todas as pessoas físicas capazes, maiores de 18 anos, que desejarem participar de forma gratuita e que possuírem um perfil válido na rede social Instagram (www.instagram.com).
          Todo o material enviado a este concurso poderá ser utilizado pelo Hotel Urbano em qualquer espécie de mídia, com os devidos créditos ao autor através da aplicação de uma marca D`agua indicando o Instagram do participante que a enviou.
          É vedada a participação de sócios e colaboradores do Hotel Urbano, assim como seus respectivos parentes de 1º grau.
          Será considerado autor da foto ou do vídeo apenas o participante que enviar a foto ou o vídeo para concurso. Este participante será o único e exclusivo responsável por obter a autorização de uso de imagem das demais pessoas que estejam nas imagens enviadas ao concurso.
        </p>
        <p>
          3. PARTICIPAÇÃO
          Para participar o usuário deve seguir os seguintes passos:
          §  Ter um perfil válido na rede social Instagram.
          §  Seguir o perfil oficial do Hotel Urbano no Instagram:  http://instagram.com/hotelurbano
          §  Marcar a foto ou o vídeo com o qual deseja participar com a hashtag #huhackday com a geolocalização ativada.
        </p>
        <p>
          Em caso de imagens ou vídeos iguais ou parecidos, será considerada o primeiro postado.
          Cada participante poderá participar do concurso com quantas imagens e vídeos quiser. O participante receberá a quantia de R$10 de crédito no site do Hotel Urbano por foto ou vídeo selecionado para uso da empresa. Além disso, o participante também receberá os devidos créditos de autor através da aplicação de uma marca D`agua em seu conteúdo, indicando o endereço do seu Instagram.
          Serão desclassificados desta promoção participações em caso de fraude comprovada, participações através da obtenção de benefício/vantagem de forma ilícita, pelo não cumprimento de quaisquer das condições deste regulamento ou pelo conteúdo expor cenas de abuso, violência, sexo, ofensas religiosas e afins.
          No caso de suspeita de fraude, poderá ser solicitado ao participante, a qualquer tempo, mesmo durante o período de participação do concurso, a apresentação de seus dados pessoais, sob pena de desclassificação imediata do mesmo.
        </p>
        <p>
          4.PREMIAÇÃO                                                                                                                       
          Cada participante poderá participar do concurso com quantas imagens e vídeos quiser. O participante receberá a quantia de R$10 de crédito no site do Hotel Urbano por foto ou vídeo selecionado para uso da empresa. Além disso, o participante também receberá os devidos créditos de autor através da aplicação de uma marca D`agua em seu conteúdo, indicando o endereço do seu Instagram.
        </p>
        <p>
          5. SELEÇÃO DAS IMAGENS E VÍDEOS
          A escolha das imagens e vídeos enviados pelos participantes, e que serão usadas pelo Hotel Urbano, deverão ser selecionadas pela equipe de Produção da empresa.
          A avaliação e escolha dessas imagens seguirá o critério da equipe responsável.
        </p>
        <p>
          6. DIVULGAÇÃO DOS SELECIONADOS
          Não haverá data de divulgação específica. O usuário será notificado assim que sua foto for selecionada pela equipe de Produção do Hotel Urbano. O participante será, primeiramente, notificado via private no Instagram onde será convidando acessar o site via um link e se cadastrar/logar no site do Hotel Urbano e concordar com os termos de uso de imagem.
        </p>
        <p>
          7. ENTREGA DO CRÉDITO
          Os ganhadores serão notificados por Instagram com um link para eles se cadastrarem ou logarem no site do Hotel Urbano. Após esse passo ele receberá em até 5 dias úteis o crédito em sua conta no Hotel Urbano.
        </p>
        <p>
          8. CONSIDERAÇÕES FINAIS
          Os participantes declaram estar cientes e de acordo com todos os itens aqui descritos, incluindo a cessão de direitos do vídeo por um período de 2 (dois) anos.
          Ao se inscreverem, os participantes garantem que as imagens e os vídeos são de sua autoria e/ou que possuem os respectivos direitos autorais e, no caso de imagens ou vídeos com pessoas, que possuem autorização das mesmas para a sua publicação e exposição. Os participantes assumem total e exclusiva responsabilidade a respeito de todas e quaisquer eventuais reivindicações de terceiros, incluindo, mas não se limitando às reivindicações de direitos de imagem e direitos autorais de terceiros que se sintam prejudicados com relação aos vídeos publicados.
          O Hotel Urbano se reserve ao direito de alterar qualquer item deste regulamento sem aviso prévio.
          Este regulamento estará disponível no endereço https://www.facebook.com/notes/hotel-urbano/regulamento-vivamaishist%C3%B3rias-instagram/850221918340019 ao longo do período de vigência do Concurso.
        </p>
      </div>
      <div class="modal-footer row">
        <a href='#' type="button" class="btn btn-default" data-dismiss="modal">Fechar</a>
      </div>
    </div>
  </div>
</div>